#MLP Regressor

In [1]:
#Basic libraries

import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import SGDRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [3]:
#Data loader

#Unity 1
dados_camera = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_seq_index_1-2422.npy")
dados_gps1 = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit1_loc_1-2422.npy")
dados_mmWave = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit1_pwr_60ghz_1-2422.npy")

#Unity 2
dados_gps2 = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit2_loc_1-2422.npy")

print(dados_camera.shape)
print(dados_gps1.shape)
print(dados_mmWave.shape)
print(dados_gps2.shape)


(2422,)
(2422, 2)
(2422, 64)
(2422, 2)


In [19]:
#Data treatment

dados_feixes = np.argmax(dados_mmWave , axis=1)
dados1 = np.column_stack((dados_gps2,dados_gps1))
print (dados1)
X=dados1
Y=dados_feixes

print(Y)


[[  33.42054916 -111.9290058    33.42034722 -111.92915278]
 [  33.42054569 -111.9290057    33.42034722 -111.92915278]
 [  33.42054224 -111.9290056    33.42034722 -111.92915278]
 ...
 [  33.4202489  -111.928985     33.42034722 -111.92915278]
 [  33.42024312 -111.9289844    33.42034722 -111.92915278]
 [  33.42023732 -111.9289838    33.42034722 -111.92915278]]
[62 62 62 ...  5  3  3]


In [27]:
#Data fit

sc1 = StandardScaler()
sc1.fit(X)

X_norm = sc1.transform(X)

Y = Y.reshape(-1,1)

sc2 = StandardScaler()
sc2.fit(Y)

Y_norm = sc2.transform(Y)



In [28]:
#Train and test sets

X_train , X_test , Y_train , Y_test = train_test_split(X_norm , Y_norm , test_size=0.7)



In [29]:
#Neural network training

rede = MLPRegressor(hidden_layer_sizes=(40,25,10) , 
                    max_iter=3000 , 
                    tol=0.000001, 
                    learning_rate_init=0.1 , 
                    solver="adam" , 
                    activation="tanh" , 
                    learning_rate="adaptive" , 
                    verbose=True,
                    shuffle=True
                   )


In [30]:
# 
rede.fit(X_train , Y_train)

c:\Users\daniel.carvalho\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1623: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.87504295
Iteration 2, loss = 0.19962221
Iteration 3, loss = 0.10662552
Iteration 4, loss = 0.07619199
Iteration 5, loss = 0.05176219
Iteration 6, loss = 0.04615593
Iteration 7, loss = 0.04037699
Iteration 8, loss = 0.03171511
Iteration 9, loss = 0.03097471
Iteration 10, loss = 0.02143559
Iteration 11, loss = 0.01507145
Iteration 12, loss = 0.01227344
Iteration 13, loss = 0.01171144
Iteration 14, loss = 0.01177874
Iteration 15, loss = 0.01194223
Iteration 16, loss = 0.01114999
Iteration 17, loss = 0.00917421
Iteration 18, loss = 0.00906752
Iteration 19, loss = 0.00848782
Iteration 20, loss = 0.00802137
Iteration 21, loss = 0.00797981
Iteration 22, loss = 0.00842176
Iteration 23, loss = 0.00794821
Iteration 24, loss = 0.00786027
Iteration 25, loss = 0.00804618
Iteration 26, loss = 0.00748976
Iteration 27, loss = 0.00941883
Iteration 28, loss = 0.00784620
Iteration 29, loss = 0.00736089
Iteration 30, loss = 0.00727618
Iteration 31, loss = 0.00826725
Iteration 32, los

MLPRegressor(activation='tanh', hidden_layer_sizes=(40, 25, 10),
             learning_rate='adaptive', learning_rate_init=0.1, max_iter=3000,
             tol=1e-06, verbose=True)

In [31]:
print(X_norm.shape)
print(Y_norm.shape)

(2422, 4)
(2422, 1)


In [32]:
#Test set predict

Y_rede_pred = rede.predict(X_test)


In [34]:
#Score

r2_rede = r2_score(Y_test,Y_rede_pred)
print(r2_rede)

0.9717350446820759
