#MLP Regressor

In [283]:
#Basic libraries

import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import SGDRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [284]:
#Data loader

#Unity 1
dados_camera = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_seq_index_1-2422.npy")
dados_gps1 = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit1_loc_1-2422.npy")
dados_mmWave = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit1_pwr_60ghz_1-2422.npy")

#Unity 2
dados_gps2 = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit2_loc_1-2422.npy")

print(dados_camera.shape)
print(dados_gps1.shape)
print(dados_mmWave.shape)
print(dados_gps2.shape)


(2422,)
(2422, 2)
(2422, 64)
(2422, 2)


In [285]:
#Data treatment

dados_feixes = np.argmax(dados_mmWave , axis=1)
dados1 = np.column_stack((dados_gps2,dados_gps1))
print (dados1)
X=dados1
Y=dados_feixes

print(X.shape)
print(Y)


[[  33.42054916 -111.9290058    33.42034722 -111.92915278]
 [  33.42054569 -111.9290057    33.42034722 -111.92915278]
 [  33.42054224 -111.9290056    33.42034722 -111.92915278]
 ...
 [  33.4202489  -111.928985     33.42034722 -111.92915278]
 [  33.42024312 -111.9289844    33.42034722 -111.92915278]
 [  33.42023732 -111.9289838    33.42034722 -111.92915278]]
(2422, 4)
[62 62 62 ...  5  3  3]


In [286]:
#Data fit

sc1 = StandardScaler()
sc1.fit(X)

X_norm = sc1.transform(X)



In [287]:
#Train and test sets

X_train , X_test , Y_train , Y_test = train_test_split(X_norm , Y , test_size=0.2)



In [288]:
#Neural network training

rede = MLPRegressor(hidden_layer_sizes=(40,25,10) , 
                    max_iter=3000 , 
                    tol=0.000001, 
                    learning_rate_init=0.1 , 
                    solver="adam" , 
                    activation="relu" , 
                    learning_rate="adaptive" , 
                    verbose=True,
                    shuffle=True
                   )


In [289]:
# 
rede.fit(X_train , Y_train)

Iteration 1, loss = 334.78664418
Iteration 2, loss = 58.20486381
Iteration 3, loss = 20.76888143
Iteration 4, loss = 11.07189935
Iteration 5, loss = 6.15924643
Iteration 6, loss = 4.10526139
Iteration 7, loss = 3.52292836
Iteration 8, loss = 3.38267190
Iteration 9, loss = 3.24981703
Iteration 10, loss = 3.46796917
Iteration 11, loss = 3.40683458
Iteration 12, loss = 3.39205166
Iteration 13, loss = 3.10371622
Iteration 14, loss = 3.00015660
Iteration 15, loss = 3.06643529
Iteration 16, loss = 2.95109798
Iteration 17, loss = 3.12366045
Iteration 18, loss = 3.06834739
Iteration 19, loss = 3.26286326
Iteration 20, loss = 3.48836775
Iteration 21, loss = 2.94188632
Iteration 22, loss = 2.92236149
Iteration 23, loss = 3.44626319
Iteration 24, loss = 3.65211415
Iteration 25, loss = 2.96569100
Iteration 26, loss = 2.93004602
Iteration 27, loss = 2.92324002
Iteration 28, loss = 2.99421736
Iteration 29, loss = 2.82326215
Iteration 30, loss = 2.76747784
Iteration 31, loss = 3.27725028
Iteration 32

MLPRegressor(hidden_layer_sizes=(40, 25, 10), learning_rate='adaptive',
             learning_rate_init=0.1, max_iter=3000, tol=1e-06, verbose=True)

In [290]:
print(X)
print(Y)


[[  33.42054916 -111.9290058    33.42034722 -111.92915278]
 [  33.42054569 -111.9290057    33.42034722 -111.92915278]
 [  33.42054224 -111.9290056    33.42034722 -111.92915278]
 ...
 [  33.4202489  -111.928985     33.42034722 -111.92915278]
 [  33.42024312 -111.9289844    33.42034722 -111.92915278]
 [  33.42023732 -111.9289838    33.42034722 -111.92915278]]
[62 62 62 ...  5  3  3]


In [291]:
#Test set predict

Y_rede_pred = rede.predict(X_test)


In [292]:
#Score

r2_rede = r2_score(Y_test,Y_rede_pred)
print(r2_rede)

0.9828407021354397
