#MLP Regressor

In [59]:
#Basic libraries

import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.linear_model import SGDRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from collections import Counter
from sklearn import model_selection, preprocessing, metrics
from sklearn import datasets, svm, metrics

In [43]:
#Data loader

#Unity 1
dados_camera = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_seq_index_1-2422.npy")
dados_gps1 = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit1_loc_1-2422.npy")
dados_mmWave = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit1_pwr_60ghz_1-2422.npy")

#Unity 2
dados_gps2 = np.load("C:\\Users\\daniel.carvalho\\OneDrive - Mob Serviços de Telecomunicações Ltda\\Área de Trabalho\\scenario1_unit2_loc_1-2422.npy")

print(dados_camera.shape)
print(dados_gps1.shape)
print(dados_mmWave.shape)
print(dados_gps2.shape)


(2422,)
(2422, 2)
(2422, 64)
(2422, 2)


In [44]:
#Data treatment

dados_feixes = np.argmax(dados_mmWave , axis=1)
dados1 = np.column_stack((dados_gps2,dados_gps1))
print (dados1)
X=dados1
Y=dados_feixes

print(X.shape)
print(Y)


[[  33.42054916 -111.9290058    33.42034722 -111.92915278]
 [  33.42054569 -111.9290057    33.42034722 -111.92915278]
 [  33.42054224 -111.9290056    33.42034722 -111.92915278]
 ...
 [  33.4202489  -111.928985     33.42034722 -111.92915278]
 [  33.42024312 -111.9289844    33.42034722 -111.92915278]
 [  33.42023732 -111.9289838    33.42034722 -111.92915278]]
(2422, 4)
[62 62 62 ...  5  3  3]


In [45]:
#Data fit

sc1 = StandardScaler()
sc1.fit(X)

X_norm = sc1.transform(X)



In [46]:
#Train and test sets

X_train , X_test , Y_train , Y_test = train_test_split(X_norm , Y , test_size=0.2)



In [47]:
#Neural network training

rede = MLPRegressor(hidden_layer_sizes=(40,25,10) , 
                    max_iter=3000 , 
                    tol=0.000001, 
                    learning_rate_init=0.1 , 
                    solver="adam" , 
                    activation="relu" , 
                    learning_rate="adaptive" , 
                    verbose=True,
                    shuffle=True
                   )


In [48]:
# 
rede.fit(X_train , Y_train)

Iteration 1, loss = 296.33829212
Iteration 2, loss = 56.89576157
Iteration 3, loss = 20.43723522
Iteration 4, loss = 10.27511758
Iteration 5, loss = 5.60132951
Iteration 6, loss = 4.15180459
Iteration 7, loss = 3.54349312
Iteration 8, loss = 3.45518812
Iteration 9, loss = 3.51066372
Iteration 10, loss = 3.14961600
Iteration 11, loss = 2.94920004
Iteration 12, loss = 2.84830002
Iteration 13, loss = 2.92788218
Iteration 14, loss = 2.91522747
Iteration 15, loss = 2.99572344
Iteration 16, loss = 3.13846766
Iteration 17, loss = 2.80084232
Iteration 18, loss = 2.72957411
Iteration 19, loss = 2.83547563
Iteration 20, loss = 2.66965920
Iteration 21, loss = 2.80913077
Iteration 22, loss = 2.84988260
Iteration 23, loss = 2.89677929
Iteration 24, loss = 2.92162127
Iteration 25, loss = 2.78942691
Iteration 26, loss = 3.44957952
Iteration 27, loss = 3.49246230
Iteration 28, loss = 2.85875031
Iteration 29, loss = 2.92516127
Iteration 30, loss = 2.91540978
Iteration 31, loss = 2.77213157
Training los

MLPRegressor(hidden_layer_sizes=(40, 25, 10), learning_rate='adaptive',
             learning_rate_init=0.1, max_iter=3000, tol=1e-06, verbose=True)

In [65]:
print(X)
print(Y)

counter = Counter(Y)

most_common = counter.most_common(1)[0][0]

most_common_2 = counter.most_common(3)

print(most_common_2)


[[  33.42054916 -111.9290058    33.42034722 -111.92915278]
 [  33.42054569 -111.9290057    33.42034722 -111.92915278]
 [  33.42054224 -111.9290056    33.42034722 -111.92915278]
 ...
 [  33.4202489  -111.928985     33.42034722 -111.92915278]
 [  33.42024312 -111.9289844    33.42034722 -111.92915278]
 [  33.42023732 -111.9289838    33.42034722 -111.92915278]]
[62 62 62 ...  5  3  3]
[(42, 126), (13, 105), (43, 93)]


In [50]:
#Test set predict

Y_rede_pred = rede.predict(X_test)


In [63]:
#Score

Score_rede = r2_score(Y_test,Y_rede_pred)
print(Score_rede)

0.9773170122654472
